redis:
  host: YOUR_REDIS_HOST
  port: YOUR_REDIS_PORT
  db: YOUR_REDIS_DATABASE
  password: YOUR_REDIS_PASSWORD

s3:
  aws_access_key_id: YOUR_AWS_ACCESS_KEY_ID
  aws_secret_access_key: YOUR_AWS_SECRET_ACCESS_KEY
  region_name: YOUR_AWS_REGION_NAME
  bucket: YOUR_AWS_S3_BUCKET_NAME
